[window]

padding = { x = 15, y = 15 }

opacity = 0.8

blur = false



[font]

normal = { family = "DMMonoNerdFont", style = "Regular" }

bold = { style = "Medium" }

italic = { style = "Italic" }

bold_italic = { style = "MediumItalic" }

#normal = { family = "MononokiNerdFont", style = "Regular" }


size = 16

[colors.bright] 
black = "#261d42"
blue = "#5d6fcc"
cyan = "#4a929a"
green = "#6fcc6d"
magenta = "#bb9af7"
red = "#ff7a93"
white = "#efeffa"
yellow = "#ffa773"

[colors.normal]
black = "#0f052d"
blue = "#5d5fc7"
cyan = "#36868f"
green = "#5fc75d"
magenta = "#ad8ee6"
red = "#f7768e"
white = "#e0dff5"
yellow = "#ff9e64"

[colors.primary]
background = "#0f052d"
foreground = "#e0dff5"

































































